### ISSUE TITLE
EVSE MODE TCP NOT CONNECTION

### ISSUE THREAD

**Issue by Mustafa19981903** [uhi22/pyPLC#21]
![Ekran Alıntısı1](https://github.com/uhi22/pyPLC/assets/63786187/eebf64c3-2f82-4247-85e1-0f38c4a8a5e4)
![Ekran Alıntısı](https://github.com/uhi22/pyPLC/assets/63786187/743fc2c4-572a-43a2-b5ee-ce77d29379db)
It came out like this, I bought it, what can I do? My car is Zoe.

**Comment by uhi22** [comment]
A little bit more context would be helpful. I understand the following:
- You have a Zoe which has a CCS connector.
- You want to use pyPLC to talk to the Zoe.
- The pyPLC runs in EVSE mode. Ok, this fits to the above use case.
- The pyPLC transmits a SetKey request to the modem, but does not get a response. This is bad. Check the presence of the modem.
- The pyPLC does not indicate that it receives SLAC messages from the car. This is bad. Can be caused by the missing modem, wrongly configured modem, missing 5% PWM, missing connection to the car.
